Fix test suite failures in NFSv4 plugins
Previously the test suite was failing with:
```
Traceback (most recent call last):
  File "./dstat", line 2846, in <module>
    main()
  File "./dstat", line 2705, in main
    scheduler.run()
  File "/usr/lib/python2.7/sched.py", line 117, in run
    action(*argument)
  File "./dstat", line 2801, in perform
    o.extract()
  File "/tmp/dstat/upstream/plugins/dstat_nfsstat4.py", line 40, in extract
    fields = line.split()
AttributeError: 'list' object has no attribute 'split'
```

This was caused by commit 56c5306554220989d7bade39924e3bf7be617990 where the
NFSv4 plugin was changed to use methods from the dstat class instead of opening
and splitting the file manually. Unfortunately it did not take into account
that dstat.splitlines also splits the fields within a line and the NFSv4 code
tried to do that again. Fix by removing the extra call to split.

Fixes: #136